# Generated by Django 4.2.2 on 2023-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='subcategory',
            field=models.CharField(choices=[('ST', 'Statment'), ('SP', 'Speech'), ('IN', 'Interview')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nation',
            name='category',
            field=models.CharField(choices=[('P', 'Party'), ('M', 'Military')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ST', 'Statment'), ('SP', 'Speech'), ('IN', 'Interview')], default='', max_length=20),
        ),
    ]
