# Generated by Django 4.2.2 on 2023-06-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_alliance_subcategory_alter_nation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ST', 'Statment'), ('SP', 'Speech'), ('IN', 'Interview'), ('M', 'Military'), ('P', 'Party'), ('NA', 'NorthernAlliance'), ('FPNCC', 'FPNCC')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Alliance',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
    ]
